# Generated by Django 2.2.4 on 2020-04-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientReminderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
